AllCops:
  Exclude:
    - spec/dummy/db/schema.rb
    - spec/dummy/node_modules/**/*
    - bin/*
  NewCops: enable
  SuggestExtensions: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LineLength:
  Exclude:
    - spec/dummy/db/migrate/*
  Max: 140
  AllowedPatterns: ['\A\s*#']

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/**/*

Lint/SuppressedException:
  Exclude:
    - spec/dummy/config/initializers/rails_anonymizer.rb

Metrics/AbcSize:
  Exclude:
    - spec/dummy/db/migrate/*
  Max: 60

Metrics/BlockLength:
  Exclude:
    - spec/dummy/config/environments/*
    - spec/**/*
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/dummy/db/migrate/*
  Max: 20

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/migrate/*
  Max: 50

Metrics/PerceivedComplexity:
  Exclude:
    - spec/dummy/db/migrate/*
  Max: 20

Naming/InclusiveLanguage:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - spec/dummy/config/application.rb
    - spec/dummy/db/migrate/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/RedundantConstantBase:
  Enabled: false
